"""Deploy compiled contracts to the configured blockchain(s).

This script reads the ABI/bytecode from backend/compiled (generated by
compile_contracts.py), then uses either Web3 or HederaClient to deploy each
contract.  The deployed addresses/IDs are printed and optionally stored in
Django settings or environment variables for later use.

Usage:
    python deploy_contracts.py
"""
import os
import json
from django.conf import settings
from backend.contracts import w3, hedera

COMPILED_DIR = os.path.join(os.path.dirname(__file__), 'compiled')

# mapping from simple contract names to output filenames
CONTRACT_FILES = {
    'PropertyNFT': 'PropertyNFT_PropertyNFT',
    'LeaseAgreement': 'LeaseAgreement_LeaseAgreement',
    'RentEscrow': 'RentEscrow_RentEscrow',
    'SavingsVault': 'SavingsVault_SavingsVault',
    'ThirdPartyPayment': 'ThirdPartyPayment_ThirdPartyPayment',
    'Reputation': 'Reputation_Reputation',
    'P2PCommunity': 'P2PCommunity_P2PCommunity',
    'MovingService': 'MovingService_MovingService',
}

RESULTS = {}

# deploy via Web3 if available
if w3.isConnected():
    account = w3.eth.accounts[0] if w3.eth.accounts else None
    for name, fname in CONTRACT_FILES.items():
        abi_path = os.path.join(COMPILED_DIR, f"{fname}.abi.json")
        bin_path = os.path.join(COMPILED_DIR, f"{fname}.bin")
        if not os.path.exists(abi_path):
            continue
        with open(abi_path) as f:
            abi = json.load(f)
        with open(bin_path) as f:
            bytecode = f.read().strip()
        contract = w3.eth.contract(abi=abi, bytecode=bytecode)
        tx_hash = contract.constructor().transact({'from': account})
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
        RESULTS[name] = {'web3_address': receipt.contractAddress}
        print(f"Web3 deployed {name} @ {receipt.contractAddress}")

# deploy via Hedera if available
if hedera.client:
    for name, fname in CONTRACT_FILES.items():
        abi_path = os.path.join(COMPILED_DIR, f"{fname}.abi.json")
        bin_path = os.path.join(COMPILED_DIR, f"{fname}.bin")
        if not os.path.exists(bin_path):
            continue
        with open(bin_path) as f:
            bytecode = f.read().strip()
        with open(abi_path) as f:
            abi = json.load(f)
        resp = hedera.deploy_contract(bytecode, abi)
        RESULTS[name] = RESULTS.get(name, {})
        RESULTS[name]['hedera_id'] = resp.get('contractId')
        print(f"Hedera deployed {name} id {resp.get('contractId')}")

print("Deployment results:")
print(json.dumps(RESULTS, indent=2))
