# Generated by Django 6.0.2 on 2026-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('property_type', models.CharField(blank=True, default='', max_length=50)),
                ('beds', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('metadataURI', models.CharField(max_length=255)),
                ('forRent', models.BooleanField(default=True)),
                ('forSale', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'property_property',
            },
        ),
    ]
