# Generated by Django 6.0.2 on 2026-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('propertyId', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('metadataURI', models.CharField(max_length=255)),
                ('forRent', models.BooleanField(default=True)),
                ('forSale', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
